name: Change Issue Status on PR Opened

on:
  pull_request:
    types: [opened]

jobs:
  change_issue_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get Issue number from branch name
        id: pr_details
        run: |
          # Получаем имя ветки и извлекаем номер Issue из него
          BRANCH_NAME=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+' | head -n 1)
          echo "${ISSUE_NUMBER}"
          echo "::set-output name=issue_number::${ISSUE_NUMBER}"

      - name: Move issue to "In Review"
        if: steps.pr_details.outputs.issue_number != ''
        run: |
          echo "Work issue to In Review IS WORK" \
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"content_id": "${{ steps.pr_details.outputs.issue_number }}", "content_type": "Issue"}' \
          https://api.github.com/projects/columns/3/cards
